/* Generated By:JavaCC: Do not edit this line. ParserREGEXConstants.java */
package uniandes.teolen.parserJavaCC.parserREGEX;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserREGEXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQUAL = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int DD = 7;
  /** RegularExpression Id. */
  int BEGIN = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int ALPHABETDECLARATION = 10;
  /** RegularExpression Id. */
  int VACIO = 11;
  /** RegularExpression Id. */
  int CADENAVACIA = 12;
  /** RegularExpression Id. */
  int MULTIPLY = 13;
  /** RegularExpression Id. */
  int PLUS = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int MAYUSCULAS = 17;
  /** RegularExpression Id. */
  int MINUSCULAS = 18;
  /** RegularExpression Id. */
  int SYMBOL = 19;
  /** RegularExpression Id. */
  int VAR = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"=\"",
    "\"|\"",
    "\":\"",
    "\"BeginERS\"",
    "\"EndERS\"",
    "\"Alphabet\"",
    "\"@\"",
    "\"$\"",
    "\"*\"",
    "\"+\"",
    "<INT>",
    "<DIGIT>",
    "<MAYUSCULAS>",
    "<MINUSCULAS>",
    "<SYMBOL>",
    "<VAR>",
    "\";\"",
    "\"{\"",
    "\",\"",
    "\"}\"",
  };

}
