/* Generated By:JavaCC: Do not edit this line. ParserRegexConstants.java */
package uniandes.teolen.parserJavaCC.parserRegex;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserRegexConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASIGNACION = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int MENOR = 7;
  /** RegularExpression Id. */
  int MAYOR = 8;
  /** RegularExpression Id. */
  int MENORIGUAL = 9;
  /** RegularExpression Id. */
  int MAYORIGUAL = 10;
  /** RegularExpression Id. */
  int IGUAL = 11;
  /** RegularExpression Id. */
  int DIFERENTE = 12;
  /** RegularExpression Id. */
  int DEF = 13;
  /** RegularExpression Id. */
  int PRINT = 14;
  /** RegularExpression Id. */
  int IFStatement = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int FALSE = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int SUMA = 21;
  /** RegularExpression Id. */
  int RESTA = 22;
  /** RegularExpression Id. */
  int MULTIPLICACION = 23;
  /** RegularExpression Id. */
  int DIVISION = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int MAY = 26;
  /** RegularExpression Id. */
  int MIN = 27;
  /** RegularExpression Id. */
  int NUMERO = 28;
  /** RegularExpression Id. */
  int VARIABLE = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"=\"",
    "\"VAR\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\" >=\"",
    "\"==\"",
    "\"!=\"",
    "\"define\"",
    "\"print\"",
    "\"if\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"false\"",
    "\"true\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<DIGIT>",
    "<MAY>",
    "<MIN>",
    "<NUMERO>",
    "<VARIABLE>",
    "\":\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
  };

}
